### ISSUE TITLE
Finalizing a file/folder naming/structure

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#10]
Thought it would be a good idea to get some consensus on the final file/folder structure

The first level is what I plan to make a snakebids standard:
<root>/
 |- config/
 |- logs/
 |- work/
 |- results/ 

Where results becomes a BIDS-derivatives dataset (i.e. will have snakebids deposit a dataset_description.json file inside)  -- note: may make sense to rename results/ to hippunfold/ 

What we should decide on is what images we include in the results/ folder, and what stays in the work/ (i.e. scratch) folder. 

Also whether we should allow the user to specify the output-space (e.g. T2w instead of T1w), and maybe output-resolution too? (maybe another issue to implement that if desired). We can try to use fmriprep-like input arguments wherever possible..

**Comment by jordandekraker** [comment]
I still feel its nice to have the cropped CorObl images (along with labelmaps, coords, and .vtk surfaces) in results/. If you were performing a morphometry study, then that space should have everything you need without the loss of detail that comes with resampling to a lower native resolution (though we should definitely also keep the native space results too).

Otherwise I'm happy with this structure!

**Comment by royhaast** [comment]
Yeah, I think this would be a nice way to structure it.

Related to @jordandekraker's comment on which data should be considered 'results', it's maybe good to think about the future next steps that users might be interested in. For example, if someone wants to sample (quantitative) T1 values onto the hippocampal mesh this might be best to do in the native resolution of that data so it's worth having the coordinates in the space that no transform is necessary (as long as the quantitative T1 map is aligned, but not resampled, to the input of autotop)?

**Comment by jordandekraker** [comment]
Yeah definitely lots of applications in which you'd also want the native space results too. Perhaps we could transform back to native without resampling? I know the resolutions will be different between, say, subfield labels and the native T1w, but I think most viewers should be able to handle this, right?

**Comment by akhanf** [comment]
Yes I agree - we should be able to concatenate into single transforms file (might have to be a .h5 transform).

Another change I will make is dropping the ability to have multiple coronaloblique templates; I don't envision now ever needing to use something other than our current CITI168 space (we can still use the same space even if we want additional contrasts for registration), so we can then use 'corobl' in the filenames instead of '{template}corobl' - this will make life easier in the workflow as we won't need to carry that wildcard around everywhere..

**Comment by akhanf** [comment]
The final segmentations, surfaces, and anatomicals are now cleaned up and saved to `results/`, with intermediate files in  `work/` from #24 

TO DO: create composed transforms to go to/from unfolded space, and store these in results

**Comment by jordandekraker** [comment]
Just a quick note: for anybody using the container its not straightforward to view output gii surfaces with subfield labels (since they are in `resources/bigbrain/sub-bigbrain_hemi-L_subfields.label.gii`. Perhaps this could be copied to the results folder (and included in the .spec file?)

**Comment by akhanf** [comment]
In the cifti branch made recently I convert those into a dlabel cifti file, that should achieve the same purpose, though we can also copy the label gii to the surf folder too..  In any case, I'll make a PR for it that we can add to.
