### ISSUE TITLE
cropseg with only one hemi

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#104]
If only one hemisphere `_dseg` file is present, then it should run only that without having to specify the `--hemi` flag. In this case, even when I specify the `--hemi` flag it still returns a weird error where it can't find the missing hemisphere in `rule copy_to_results`. It only works if I use `--path_cropseg` and include the {hemi} wildcard there. 
I think this issue depends on whether `hemi` is specified in the config or as a {wildcard}, but I'm not sure how to solve it.

**Comment by akhanf** [comment]
would be good to have a test case to investigate this with dry-run -- can you make a branch with this in the test_data folder? could perhaps just copy the data_cropseg and delete one hemisphere?

**Comment by akhanf** [comment]
Just getting to this now --

For `--modality cropseg` it is actually buggy using pybids parser, and so should only use `--path_cropseg`. Pybids (or at least the older version we are using, or the way we are using it) doesn't pick up the `hemi` entity, so it doesn't interpret hemi as a wildcard. E.g. if you had both L & R hemis and used the bids parser, then it would pick up the same image (e.g. L) as both the L and R, which is bad.. We should actually try to flag this somewhere so it fails with an error. But at least we should make this correction in the documentation.

As for getting things to behave with `--path_cropseg` I found some spots where the wildcard constraints were needed (e.g. for density), so looks like that fixes it. Will open a PR for you to try it out.
