### ISSUE TITLE
Incorrect label names in label.gii files

### ISSUE THREAD

**Issue by alexander-ngo** [khanlab/hippunfold#107]
Hi,

I noticed that the label names might be incorrect when I loaded the label.gii.files on MATLAB. Should it be `{'???' 'Subiculum' 'CA1' 'CA2' 'CA3' 'CA4'}`?

<img width="504" alt="Screen Shot 2021-09-14 at 18 43 26" src="https://user-images.githubusercontent.com/65247338/133343466-2d00d105-2bab-4bc5-8369-4fd35a22d07e.png">

**Comment by jordandekraker** [comment]
Thanks Alexander! I'll try to correct this sometime in the next few days.

**Comment by akhanf** [comment]
fixed in #108
