### ISSUE TITLE
renaming/refactoring output directories

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#127]
1. autotop directories in the work folder should live inside another folder
2. 'seg_{modality}' doesn't make sense - vol? (to go with surf?)
3. xfm or transform folder to store warps? (or warps?)
4. think about a coords folder (or subfolder?)
5. only allow user to specify 1 modality at a time  -- this would allow removal of the {modality} wildcard in filenames/folders and simplify outputs alot

6. workflow mode vs bids app:
```
workflow mode:
-results/sub-
-results/work
logs

bidsapp mode:
sub-
work
logs

config['root'] 
```

**Comment by akhanf** [comment]
point 5. above is dealt with in #137

**Comment by jordandekraker** [comment]
I think that we should change `seg` to `vol`, merge it with `anat` (which is typically nearly empty), and then place `warps` and `coords` subfolders inside that. I think this would be fine for both `work` and `root`. @akhanf thoughts?

Related bug: `from-unfold_to-corobl_mode-image_xfm` files are showing up in the results and i'm not sure why - I don't see them in the `common.smk` or in the `warps.smk`

**Comment by akhanf** [comment]
instead of subfolders for warps and coords, we could just make them siblings, e.g. contents of `hippunfold/sub-001` could be:
```
vol
warps
coords
surf
```

actually regarding naming of the `vol` folder, I think I actually prefer to just call it `anat`, as it would contain the `_{T1w/T2w}.nii.gz` and `_dseg.nii.gz` images, so from a BIDS perspective that would be the required location for those BIDS derivatives files. It also leaves the door open for `func` and `dwi` folders, e.g. when we get around to adding rules to import and resample that data..

**Comment by akhanf** [comment]
re: that `from-unfold_to-corobl_mode-image_xfm` file showing up in results, I can take a look, it could be using `root=root` in some generic rule.. 

In any case, we should probably finish merging in  #153 before we branch with more refactoring to make our lives easier
