### ISSUE TITLE
wrong dseg for templateshapeinjection

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#141]
If running hippunfold after a previous failure, sometimes this function will pull the templateshape (copied to anat/) thinking it is the nnunet segmentation: https://github.com/khanlab/hippunfold/blob/68fce707cb976458e71d12cda8f56abbaa509e68/hippunfold/workflow/rules/shape_inject.smk#L3

**Comment by akhanf** [comment]
Is there a way to reproduce this error? Does this only happen with `--keep-incomplete`?

**Comment by jordandekraker** [comment]
I believe this was occurring `with `--modality cropseg` and the rest default options, but I havent been able to reproduce the issue (I think it was because I was in the middle of making change and so the workflow was breaking in a weird place. Looking at this line again I think it should be fine.
