### ISSUE TITLE
error in rule run_inference

### ISSUE THREAD

**Issue by x-avent** [khanlab/hippunfold#165]
Hi,
I tried to run HippUnfold on my data but keep getting an error in the run_inference step (details below).
Any ideas about what may cause this issue are very much appreciated! 
Please let me know if you need any further information.
Thank you, 
xenia

----------------------------
error run_inference details:
----------------------------
My command: 

> _docker run -it --rm -v ~/PatCom/my_dataset:/bids:ro -v ~/PatCom/hippunfoldPatComTest:/output khanlab/hippunfold:latest /bids /output participant --modality T1w --cores all_

The error message:

_> rule run_inference:
>     input: work/sub-001/anat/sub-001_hemi-R_space-corobl_desc-preproc_T1w.nii.gz, /opt/hippunfold_cache/trained_model.3d_fullres.Task101_hcp1200_T1w.nnUNetTrainerV2.model_best.tar
>     output: work/sub-001/anat/sub-001_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
>     log: logs/sub-001/sub-001_hemi-R_space-corobl_nnunet.txt
>     jobid: 76
>     wildcards: subject=001, hemi=R
>     threads: 6
>     resources: tmpdir=/tmp, gpus=0, mem_mb=16000, time=60
> 
> /bin/bash: line 1:   256 Killed                  nnUNet_predict -i tempimg -o templbl -t Task101_hcp1200_T1w -chk model_best --disable_tta &> logs/sub-001/sub-001_hemi-R_space-corobl_nnunet.txt
> 
> Error in rule run_inference:
>     jobid: 0
>     output: work/sub-001/anat/sub-001_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
>     log: logs/sub-001/sub-001_hemi-R_space-corobl_nnunet.txt (check log file(s) for error message)
>     shell:
>         mkdir -p tempmodel tempimg templbl && cp work/sub-001/anat/sub-001_hemi-R_space-corobl_desc-preproc_T1w.nii.gz tempimg/temp_0000.nii.gz && tar -xf /opt/hippunfold_cache/trained_model.3d_fullres.Task101_hcp1200_T1w.nnUNetTrainerV2.model_best.tar -C tempmodel && export RESULTS_FOLDER=tempmodel && export nnUNet_n_proc_DA=6 && nnUNet_predict -i tempimg -o templbl -t Task101_hcp1200_T1w -chk model_best --disable_tta &> logs/sub-001/sub-001_hemi-R_space-corobl_nnunet.txt && cp templbl/temp.nii.gz work/sub-001/anat/sub-001_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Exiting because a job execution failed. Look above for error message
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /output/.snakemake/log/2022-02-03T142958.386969.snakemake.log_

The log doesn't show any error (see attachment).

The file sub-001_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz is not created but to my understanding the inputfile sub-001_hemi-R_space-corobl_desc-preproc_T1w.nii.gz looks good. 

The dry run with docker worked.

My dataset is a whole-brain T1w image 0.8 iso; I also provide a T2w image (0.4 x0.4 in-plane).

Please find the following files attached:
1.) the whole command-line output
2.) the latest log

[command_line_output_error_run_inference.txt](https://github.com/khanlab/hippunfold/files/7995650/command_line_output_error_run_inference.txt)
[sub-001_hemi-R_space-corobl_nnunet.txt](https://github.com/khanlab/hippunfold/files/7995659/sub-001_hemi-R_space-corobl_nnunet.txt)

**Comment by akhanf** [comment]
Hi Xenia,

Very odd that it is dying there with no sign of issue in the log -- I am wondering if maybe that process is being killed for some reason, maybe hitting some resource limit? Is this being run on your personal desktop or a cluster?  Can you provide any details on the system (os, specs, if there is a gpu on the system)? 

Can try running with `--cores 1` to see if running without any parallelization makes a difference (in case it is something resource-related)?

Ali

**Comment by x-avent** [comment]
Hi Ali,
I tried to run it with --cores 1 but get the same issue.

I didn't run it on a cluster. Here the details of my macbook pro:

macOS Big Sur
<img width="251" alt="Screenshot 2022-02-03 at 23 58 18" src="https://user-images.githubusercontent.com/86932649/152449197-ed552155-4858-43bd-94db-4f83b0937e21.png">

Is there any I can check whether this templbl/temp.nii.gz  file got created?

Xenia

**Comment by akhanf** [comment]
Using the `--keep-incomplete` flag might keep the files around, but they would be hidden away in `.snakemake/shadow` in the output folder.

Does the error happen for other datasets too? 

I'm a bit stumped on this one! It could be some strange incompatibility, we haven't been testing with docker on Mac.

**Comment by akhanf** [comment]
Ah, I figured it out -- 
Docker on Mac actually has additional resource settings for the virtual machine it runs, and by default the memory is set to 2GB. 

If you go into Docker Desktop -> Settings -> Resources, you should see settings for CPUs and memory. Upping the memory should fix the problem. I just set mine to max out, but I think anything higher than 2GB should fix the problem (it seems to be allocating around ~2.5 GB at that step).. You can also increase the number of CPUs to bump up performance..

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/11492701/152577874-2dea08d9-a4c7-4c97-b257-a04988173842.png">

Let me know if that fixes the problem.

**Comment by x-avent** [comment]
That sounds very promising! Thank you,Ali!
I will try it out tomorrow and let you know.

**Comment by x-avent** [comment]
That's the fix. It ran without problems.
Thank you very much for your help!
