### ISSUE TITLE
error with tempmodel/nnUNet

### ISSUE THREAD

**Issue by sheyma** [khanlab/hippunfold#173]
Hi all,

running this code below:

```
$ conda activate laplac
$ export HIPPUNFOLD_CACHE_DIR=/data/p_02542/dekrak/.cache/hippunfold/ 
$ hippunfold hcp-structural-preprocessed out  participant --modality T1w --cores all --use-singularity 
```

I have got the following error:

```
Error in rule run_inference:
    jobid: 0
    output: work/sub-561444/anat/sub-561444_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
    log: logs/sub-561444/sub-561444_hemi-R_space-corobl_nnunet.txt (check log file(s) for error message)
    shell:
        mkdir -p tempmodel tempimg templbl && cp work/sub-561444/anat/sub-561444_hemi-R_space-corobl_desc-preproc_T1w.nii.gz tempimg/temp_0000.nii.gz && tar -xf /data/p_02542/dekrak/.cache/hippunfold/trained_model.3d_fullres.Task101_hcp1200_T1w.nnUNetTrainerV2.model_best.tar -C tempmodel && export RESULTS_FOLDER=tempmodel && export nnUNet_n_proc_DA=16 && nnUNet_predict -i tempimg -o templbl -t Task101_hcp1200_T1w -chk model_best --disable_tta &> logs/sub-561444/sub-561444_hemi-R_space-corobl_nnunet.txt && cp templbl/temp.nii.gz work/sub-561444/anat/sub-561444_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/p_02542/dekrak/data/out/.snakemake/log/2022-02-17T093626.902876.snakemake.log
```

**Comment by jordandekraker** [comment]
Could you attach or copy the text in `logs/sub-561444/sub-561444_hemi-R_space-corobl_nnunet.txt`?

**Comment by sheyma** [comment]
[sub-561444_hemi-R_space-corobl_nnunet.txt](https://github.com/khanlab/hippunfold/files/8110268/sub-561444_hemi-R_space-corobl_nnunet.txt)

**Comment by jordandekraker** [comment]
Hmm can you also just check whether `work/sub-561444/anat/sub-561444_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz` (or a similar filename) exists?

**Comment by sheyma** [comment]
`work/sub-561444/anat/sub-561444_hemi-R_space-corobl_desc-nnunet_dseg.nii.gz
`
exists.

**Comment by jordandekraker** [comment]
Can you try re-running the original call to hippunfold (ie. `hippunfold hcp-structural-preprocessed out  participant --modality T1w --cores all --use-singularity`)? you might also need to use the `--unlock` argument

I suspect that this step succeeded but this warning message is causing the workflow to stop. Now that the file actually exists I'm hoping it will simply pick up where it left off

**Comment by sheyma** [comment]
it looks running, though hasn't yet come to the subject `sub-561444`

**Comment by jordandekraker** [comment]
Since this has now completed, i'm closing the issue
