### ISSUE TITLE
reference atlas path

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#19]
Mathilde (Konrad's lab) is having this issue using containerized version:
![image](https://user-images.githubusercontent.com/25106300/104338091-266e0600-54c4-11eb-8c5f-cd6c1064031e.png)

Which appears to stem from this line:
https://github.com/khanlab/hippunfold/blob/2d13299cca1c68fea8a3fe76097abb2eb0d4855c/hippunfold/workflow/rules/preproc_t1.smk#L38
This line should be written to return `/src/atlases/CITI/CIT168_T1w_head_700um.nii.gz` (based on what I can see inside singularity shell). 
@akhanf would you mind taking a quick look?

**Comment by akhanf** [comment]
hmm might be an old container -- just confirming that now -- did you pull it fresh from docker hub?

**Comment by jordandekraker** [comment]
fresh as of yesterday

**Comment by akhanf** [comment]
Actually looks like the circleci isn't getting the hippocampal_autotop submodule -- not sure how it worked in my earlier test! In any case, making some edits to circleci to do a recursive clone, and will rebuild the container -- hopefully should be good to go by end of day!

**Comment by jordandekraker** [comment]
Oops my copy of the image was old (ie. the atlases should NOT be in `/src/atlases/CITI/CIT168_T1w_head_700um.nii.gz` but i'm stil not sure where they should be as `/opt/conda/lib/python3.7/site-packages/hippunfold/hippocampal_autotop/` does not exist. Maybe you forgot to pull submodules when building the docker container?

**Comment by jordandekraker** [comment]
Yup! looks like it wasn't pulling submodules. Looks like '--recursive-submodules` is needed rather than `--recursive`.
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by akhanf** [comment]
--recursive will do it too, but circleci has it's own checkout step which doesn't do --recursive, so now I've replaced that, seems to be rebuilding now, hopefully once done it should work: 
https://app.circleci.com/pipelines/github/khanlab/hippunfold/72/workflows/0a910b7f-a97d-43e8-a482-e2b52d6722e4/jobs/140

Note that the file gets to be in the site packages through `pip install`, as the `MANIFEST.in` contains the paths to the non-python files to also include in the package..

**Comment by akhanf** [comment]
ok, looks like the new container fixes this problem, can close once you confirm @jordandekraker @myousif9

**Comment by jordandekraker** [comment]
Confirmed, its working for me now!

**Comment by myousif9** [comment]
Works for me too!
