### ISSUE TITLE
`.snakebids` file not found

### ISSUE THREAD

**Issue by romeopenheiro** [khanlab/hippunfold#191]
I performed a dry run of the Docker as per the instructions on the Hippunfold Installation instructions and ran into an error (see screenshot below).

<img width="885" alt="Screen Shot 2022-06-03 at 6 05 17 AM" src="https://user-images.githubusercontent.com/50489128/171834507-07e60d11-d65e-4e6e-a08e-ca9a2cefaa10.png">

It seems that the app ".snakebids" is required in the out directory but I am not sure how to do that. I am new to using a BIDS App like Hippunfold, so some guidance on this would be really helpful. 

The CLI code that I used is below:

<img width="704" alt="Screen Shot 2022-06-03 at 6 05 06 AM" src="https://user-images.githubusercontent.com/50489128/171834644-74d5e402-e655-4817-bb6d-ed1859cc8692.png">

If you require further information, please let me know.

**Comment by akhanf** [comment]
Ah, this error is popping up because the output folder already exists. If you set the hippunfold output to a folder that does not exist yet, then hippunfold will create it (and make the .snakebids file itself). 

I realize now that this conflicts with the docker instructions, so I'm going to make a patch so it will work even if the folder exists, but for now, what you can do is something like this:

```
docker run -it --rm -v PATH_TO_DATA_DIR:/data  khanlab/hippunfold:latest /data/bids /data/outputnewfolder participant
```

**Comment by akhanf** [comment]
Ok I've made a fix as well so your original command should work now -- though you will need to pull the khanlab/hippunfold:master container instead of latest (until we make a new release).

Let me know if you're able to get going either way.

**Comment by romeopenheiro** [comment]
This worked for me. However, I got into another issue.

I followed your instructions and pulled the khanlab master container (instead of latest):

`docker pull khanlab/hippunfold:master`

Then, I did a dry run using the following line of code:

`sudo docker run -it --rm \ 
-v /Users/RomeoPenheiro_1/ds003592-download:/bids:ro \
-v /Users/RomeoPenheiro_1/ds003592-download:/output \
khanlab/hippunfold:master \
/bids /output participant -np --modality T1w`

Unfortunately, this didn't work and I got the following error:

`Output dir "/output" exists, but ".snakebids" file not found. Please specify either a new directory, or a `

Therefore, I tried with `/outputnewfolder` and that solved the problem. The code is below:

`sudo docker run -it --rm \
-v /Users/RomeoPenheiro_1/ds003592-download:/bids:ro \
-v /Users/RomeoPenheiro_1/ds003592-download:/output \
khanlab/hippunfold:master \
/bids /outputnewfolder participant -np --modality T1w`

So, I tested this out on the data of `sub-01` using the following lines of code:

`sudo docker run -it --rm \
-v /Users/RomeoPenheiro_1/ds003592-download:/bids:ro \
-v /Users/RomeoPenheiro_1/ds003592-download:/output \
khanlab/hippunfold:master \
/bids /outputnewfolder participant --participant_label 01 --modality T1w --cores all`

I ran this in my terminal, and after two days of running, I received the following error:

<img width="1173" alt="Screen Shot 2022-06-27 at 10 09 37 AM" src="https://user-images.githubusercontent.com/50489128/175961506-8709c443-dc5e-4223-8d08-fd01aa0699b5.png">


I noticed in the message above that a snakemake log was created but I am not sure how to access it through the terminal to figure out what may have happened. The total size of my docker image on disk is 32.8GB and I am left wondering if that has anything to do with this. Any suggestions on the next steps would be really appreciated. Thank you!

**Comment by akhanf** [comment]
looks like this is the same issue as #197 - I've got things set-up now on my mac so I can try to debug.. it may be some weird interaction with docker in this case..

**Comment by akhanf** [comment]
Please see my post in the other isse #197. Sorry I don't think we are able to support running on Apple M1 using docker.

**Comment by romeopenheiro** [comment]
Hello! Thanks for the quick response. 

I signed up for an account to use hippunfold 1.0.0 in CBRAIN and tried to run the same analysis through the web-based ui there but it did not work and I don't know why. I used the same parameters as I was using with Docker previously:

<img width="306" alt="Screen Shot 2022-06-29 at 11 14 13 AM" src="https://user-images.githubusercontent.com/50489128/176472598-ba5d1620-99c8-41bb-90ce-55c11bd5a415.png">

Unfortunately, the data processing failed on the cluster:
<img width="1225" alt="Screen Shot 2022-06-29 at 11 14 35 AM" src="https://user-images.githubusercontent.com/50489128/176472669-371ef018-999d-4aaf-acb8-475ea55c9e03.png">

Also, the output error is the following:
<img width="769" alt="Screen Shot 2022-06-29 at 11 18 59 AM" src="https://user-images.githubusercontent.com/50489128/176473722-6584de04-a9d5-4ad7-90c3-c13ce3b9e0b8.png">

The `sub-01` is from the following online dataset: https://doi.org/10.18112/openneuro.ds003592.v1.0.11

I am not sure where to go from here. Do you have any suggestions?

**Comment by romeopenheiro** [comment]
Hi. Just wanted to follow-up and close this issue.

I was able to figure out the problem and solve it. My data were in two sub-directories so the program was not able to begin the analysis. Once I formatted the directory structure according to BIDS, things worked smoothly.

**Comment by akhanf** [comment]
Great to hear! I've also started the process to have our 1.1.0 version set-up on CBRAIN, can follow that here if you're interested (hopefully shouldn't take long..): https://github.com/aces/cbrain-plugins-neuro/issues/238
