### ISSUE TITLE
adding new CNNmodel for 1mmT1w data

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#21]
Wanted to ship a new CNNmodel trained on downsampled HCP1200 data, for better inference in Konrad's work on the MELD dataset. I can't seem to get the snakemake pipeline to connect input T1w data to the new CNN model though. @akhanf would you be able to take a look?

https://github.com/khanlab/hippunfold/tree/modality_1mmT1

**Comment by akhanf** [comment]
sure I'll turn this into a PR to make some edits

**Comment by akhanf** [comment]
closing this since addressed in #23
