### ISSUE TITLE
DG surface contains self-intersection

### ISSUE THREAD

**Issue by debinz** [khanlab/hippunfold#241]
Dear professionals of Hippunfold,

I employed this tool to generate a midthickness hippocampus surface, selecting a 2mm resolution. While examining the results I found that the dentate gyrus surface exhibited self-intersection indicating that an edge of the mesh contacts the surface itself(see accompanying figure). This case would impact the subsequent feature sampling like BOLD signals and other geometric analyses. 

I used the latest version of v1.2.1 and run this tool using singularity. Could you kindly offer me some advice to deal with this issue?

Best regards,
Debin

![image](https://github.com/khanlab/hippunfold/assets/24296206/e8d318e0-99a9-4939-bb53-428422d2960c)

**Comment by akhanf** [comment]
I'll also add that these issues are less prominent if a denser surface sampling is used (e.g. 0p5mm), so I would try that first.

**Comment by debinz** [comment]
Great! Thank you for sharing the tool and the atlas. This will definitely be helpful for downsampling and considering the combination of DG and CA4 labels. Appreciate your response!

**Comment by jordandekraker** [comment]
Closing, but let me know if you have further issues and I can reopen!
