### ISSUE TITLE
process HCP fmri on hippunfold results

### ISSUE THREAD

**Issue by raywell627** [khanlab/hippunfold#248]
Hi hippunfold expert:
I'm trying to extract fmri signal from HCP dataset. But HCP only include MNI space fmri data. I tried to register the fmri data back to native space and then project it onto the hippocampus subfields. i'm not sure if this introduces some bias of bold signal. Is there a best way to process HCP fmri data ? Can you kindly gave some advice about this problem ? 
Thank you for your help!
best regards
carlos

**Comment by jordandekraker** [comment]
Hi Carlos,

The easiest way to make sure your fMRI data is aligned to HippUnfold is simply to run HippUnfold on data that is also in space-MNI152. I believe that in HCP these data are rigidly aligned to MNI, and so there will still be a lot of inter-individual variability in hippocampal shape, which HippUnfold should be able to detect.

I hope that helps,

**Comment by jordandekraker** [comment]
Closing, but let me know if you have further issues and i can reopen!
