### ISSUE TITLE
failed autotop.smk leaves no outputs for inspection

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#25]
When segmentation fails and throws an error, the corobl folder is deleted (unless `--keep-incomplete` is added), which makes for rather confusing troubleshooting. Not a big deal, but passing this flag by default would certainly make this easier for new users.

**Comment by akhanf** [comment]
this would be a snakebids change, but not really crazy about adding default snakemake options, since there isn't a way to un-set an option, and snakemake profiles can be used to set default options.. Closing this issue for those reasons..
