### ISSUE TITLE
Naming of histologyReference2023

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#254]
@jordandekraker I didn't pay attention to this when reviewing the initial PR, but the naming for this atlas could be improved. It seems nit-picky but it's something we would have to live with for some time, so I think it's not too late to finalize it (ie before paper is published, and before many people start using it) 

- the use of the word "Reference" is redundant (any atlas is being used as a reference)..
- the name is really long, and uses camelCase which goes against the existing naming scheme and bids style
- we haven't been using years in any naming for other atlases etc so the 2023 feels out of place..
- what is quite novel over the previous `bigbrain` atlas is this is built from 7 datasets instead of the bigbrain pair of hippocampi, but this isn't apparent from the name

What do you think of renaming this atlas to be `histology7` instead? It is shorter, and conveys more meaning than the previous name.. or `multihist7`? 

By the way, what about also publishing the probabilistic labels for each subfield?

**Comment by jordandekraker** [comment]
All good points! I slightly prefer `multihist7`, but have no strong opinion.

Let me know if you have a preference, and I'll create a PR

**Comment by akhanf** [comment]
Great! I agree multihist7 works well. Was a simple git mv and rename, so made the PR already, will merge it in since it's a straighforward PR..

**Comment by jordandekraker** [comment]
closed with https://github.com/khanlab/hippunfold/pull/256
