### ISSUE TITLE
sample functional data along surface

### ISSUE THREAD

**Issue by vipfa100** [khanlab/hippunfold#257]
Dear hippunfold folks,

I am trying to sample my high-res functional data along the surfaces generated by hippunfold. I use matlab for that by reading in  the inner and outer surface gifti files. In order to bring those surfaces into matlab space (i.e. shift them around such that if I plot them in matlab over the image to be sampled, they are nicely confined to the anatomical boundaries) I use the following transformations:

![image](https://github.com/khanlab/hippunfold/assets/73169480/77a2e97d-a68b-45ed-8309-5ce746f0b961)

`surf = surf/0.75;`   % divide surfaces by image resolution to achieve units of voxels not mm

`surf = bsxfun(@times,surf,shift);`  
% shift is a 1x3 vector corresponding to a change in sign depending on whether the image was acquired on a different plane, i.e. sagittal as opposed to transversal.

`surf = bsxfun(@minus,(0.5*dims),surf)` % shift the surfaces by half the size of the image. dims is the size of the image.

This approach always works for surfaces generated by freesurfer but not so for hippunfold surfaces. In fact, to obtain the image above, I ran the code and additionally shifted the surfaces by some voxels but this shift is subject specific so this is not really practial.

My question is: What is the underlying transformation between freesurfer and hippunfold surfaces? This maybe relate to the error one gets when first loading the volume and then the surfaces in freeview instead of the other way around but I cannot really wrap my head around the underlying transformations. 

Any idea of where I can search for?

Many thanks for the help and also for this awesome toolbox!!

Viktor

**Comment by vipfa100** [comment]
Thanks for the very fast reply!

Yeah I am aware of the workbench tool. It would maybe result in a bit of a file mess given that for each layer, hemisphere and volume on file is created, e.g. for 100 vols and 20 layers, I would have 4000 files. In the end it will results in toggling between creation and deletion I guess but I first want to try out your matlab suggetions. 

Just to be clear: 
*in `header = niftiinfo(file)` I have a field `header.Transformation`. You're referring to this, right?
* with `invert(tform)` you mean to invert `header.Transformation`?

**Comment by jordandekraker** [comment]
Ahh yes, `header.Transformation` should be correct!

**Comment by vipfa100** [comment]
Awesome your 2nd point works like a charm!! Many thanks! Haven't seen such a good support for a very long time :)

**Comment by akhanf** [comment]
FYI (mainly for anyone else coming across this issue) -- you can use `wb_command -volume-to-surface-mapping` to sample 4D nifti data (not just 3D), so it would be one `func.gii` file for your 100 volumes. You could even then use cifti to put all the layers in the same file too.. 

> Yeah I am aware of the workbench tool. It would maybe result in a bit of a file mess given that for each layer, hemisphere and volume on file is created, e.g. for 100 vols and 20 layers, I would have 4000 files. In the end it will results in toggling between creation and deletion I guess but I first want to try out your matlab suggetions.

**Comment by vipfa100** [comment]
Ha that is actually very good to know! Many thanks!

**Comment by vipfa100** [comment]
Hi all,

a quick follow-up regarding the workbench command: If I want to run the following command

`wb_command -volume-to-surface-mapping volume.nii lh.white.gii out.func.gii -cubic -volume-roi roi.nii ` I get the error message `Unexpected parameter: -volume-roi`. Am I messing with the function call?

**Comment by vipfa100** [comment]
Uff, totally overseen this. Sorry for bothering and thank you again for the fast reply!
