### ISSUE TITLE
Tutorial for transforming BigBrain to MNI

### ISSUE THREAD

**Issue by andreifoldes** [khanlab/hippunfold#258]
Thank you for developing this tool! 

I was thinking that it would be useful rs and task-fmri people if there was a tutorial on the ideal way to transform anatomical masks from BigBrain to MNI? I would specifically be most interested in MNI152NLin2009cAsym or MNI152NLin6Asym.

**Comment by akhanf** [comment]
There is https://bigbrainwarp.readthedocs.io/en/latest/ for general warps between bigbrain and template spaces. 

If you want hippunfold outputs in a template space you could also run hippunfold directly on the template. I've actually done this already for templateflow templates (incl MNI templates) and shared outputs here: 

https://github.com/khanlab/hippunfold-templateflow

**Comment by andreifoldes** [comment]
> There is https://bigbrainwarp.readthedocs.io/en/latest/ for general warps between bigbrain and template spaces.
Thanks, that amazing!

> If you want hippunfold outputs in a template space you could also run hippunfold directly on the template. I've actually done this already for templateflow templates (incl MNI templates) and shared outputs here:
> 
> https://github.com/khanlab/hippunfold-templateflow

Neat! I thought would be best practice to run hippunfold on the native T1w...

**Comment by akhanf** [comment]
Yes it is definitely best practice to run on native T1w, so hippunfold on templateflow is mainly for cases when the data is only in a template space, or you don't have access to the native T1w images.
