### ISSUE TITLE
errors while running hippunfold with slurm & snakemake

### ISSUE THREAD

**Issue by vnbcs** [khanlab/hippunfold#282]
> TLDR: I added Snakemake slurm cluster execution arguments to a Hippunfold command. Now the program is crashing with a "variable referenced before assignment" error. The original Hippunfold command (without the cluster execution arguments) ran without issue. Can someone help me figure out what is going wrong?

I am running Hippunfold on a very large amount of data using slurm (job scheduler). I have been having issues with my jobs timing out prior to completion. I am running smallish batches of subjects (~500, some with multiple scan sessions) concurrently. It looked like a decent amount of the data finished running, but I wanted to be sure, so I opened [an issue](https://github.com/khanlab/hippunfold/issues/273) asking how to know if subjects are fully processed... and it turns out none of the subjects finished running 😭 

In response to my previous issue, @jordandekraker mentioned that Snakemake can submit its own jobs via slurm. I have no experience using workflow managers such as Snakemake. I asked for advice from the folks at my university's supercomputing center, but they are more familiar with Nextflow (another workflow manager). 

I added some Snakemake arguments to my Hippunfold slurm script, and have been testing one subset of the data. My last few jobs have exited out with the exact same error. Unfortunately, each job takes 3-4 hours to crash, which makes debugging slow. Here's my latest submission script:

```bash
#!/bin/bash
#SBATCH --account=jhanson
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=48
#SBATCH --cluster=mpi
#SBATCH --partition=mpi
#SBATCH --time=72:00:00
#SBATCH --output=abcd_logfiles/abcd_subset1_head-%j.out 
#SBATCH --job-name=headSubset1

unset TMPDIR

module load singularity

export SIFILE=khanlab_hippunfold_latest.sif
export INFOLD=abcd-mproc-release5/abcd_subset1
export OUTFOLD=abcd_hippunfold

singularity run -e $SIFILE $INFOLD $OUTFOLD \
participant -p --cores 8 --modality T1w \
--keep-going --force-output --slurm --default-resources slurm_account=jhanson slurm_partition=mpi --jobs 48
```

The cluster execution arguments are `--slurm` and everything after it. I also added `unset TMPDIR`, which was advised by the supercomputing folks. 

Here's the tail end of the error:

```
File "/opt/conda/lib/python3.9/site-packages/snakemake/executors/slurm/slurm_submit.py", line 29, in get_account
    cmd = f'sacct -nu "{os.environ["USER"]}" -o Account%256 | head -n1'
  File "/opt/conda/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'
local variable 'res' referenced before assignment
```

Here are the last two log files, including the full error output:
[abcd_subset1_head-2076642.txt](https://github.com/khanlab/hippunfold/files/14350239/abcd_subset1_head-2076642.txt)
[abcd_subset1_head-2076633.txt](https://github.com/khanlab/hippunfold/files/14350241/abcd_subset1_head-2076633.txt)

**Comment by Bradley-Karat** [comment]
Heres a shot at what I think you are running into (@akhanf or @jordandekraker feel free to weigh in):
The singularity container itself does not have access to slurm and its subsequent commands. At the top of your log file the first error thats thrown is this: `Error message: /bin/sh: 1: sacct: not found` where the slurm command sacct can't be found.

Given the number of subjects you have, a good option may be to use job arraying with sbatch (see https://docs.alliancecan.ca/wiki/Job_arrays for example). To set this up, your sbatch script could look like the following:
```
#!/bin/bash
#SBATCH -p partition
#SBATCH --begin=now
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 16
#SBATCH --mem-per-cpu=1024M
#SBATCH --array=1-3 #spawn 3 jobs each with the specified resources
#SBATCH --time=0-03:00           # time (DD-HH:MM)
#SBATCH --output hippunfold_array-%a_log.out

participant=$(sed -n "${SLURM_ARRAY_TASK_ID}p" participants.txt | cut -c5-) #Can remove the "cut -c5-" 
if you don't have the "sub-" prefix in the participants.txt file. 

echo "Starting task $participant"

singularity run -e khanlab_hippunfold_v1.4.1sif /inputs/bids/directory /output/hippunfold/directory \
participant -p --modality T1w --keep-work --participant-label "$participant" --cores all
```
where the `participants.txt` in this example looks like:
```
sub-01
sub-02
sub-03
```
This will spawn 3 separate hippunfold jobs, one for each subject each with 16 cpus and 3 hours, effectively parallelizing across subjects and not burdening the scheduler since we are submitting multiple jobs from this one script.

Let me know if this works for you!

**Comment by vnbcs** [comment]
@Bradley-Karat Thank you so much! I've been working on adapting the script to my situation. Currently, I am running the following:

```sh
module load singularity

export SIFILE=khanlab_hippunfold_latest.sif
export INFOLD=abcd-mproc-release5/abcd_subset1
export OUTFOLD=abcd_hippunfold

# remove the "cut -c5-" if you don't have the "sub-" prefix in the participants.txt file
participant=$(sed -n "${SLURM_ARRAY_TASK_ID}p" test_participants.txt | cut -c5-)  

echo "Starting task $participant"

singularity run -e $SIFILE $INFOLD $OUTFOLD participant -p --modality T1w \
--keep-work --participant-label "$participant" --cores all --keep-going --force-output
```

I submitted it multiple times, and each time, the jobs start running, and then error out due to not being able to find the T1ws. Here are the error messages from the last three jobs:

[hipp_array_subset1-1_log.txt](https://github.com/khanlab/hippunfold/files/14409091/hipp_array_subset1-1_log.txt)
[hipp_array_subset1-2_log.txt](https://github.com/khanlab/hippunfold/files/14409089/hipp_array_subset1-2_log.txt)
[hipp_array_subset1-3_log.txt](https://github.com/khanlab/hippunfold/files/14409087/hipp_array_subset1-3_log.txt)

In logs 2 and 3, the data actually started running. Each job ran for an increasing amount of time - job 1 crashed immediately, job 2 ran for 5ish minutes, and job 3 ran for 10ish minutes. I am continuing to troubleshoot. If you have any suggestions, I would appreciate it!

@akhanf This sounds interesting! It takes 5+ minutes to build the DAG with every method I have tried so far, so I worry this would take forever. I will keep this in mind in case I can't get job arrays to work.

Re: parallel processing: When my jobs were timing out, I was already running multiple jobs in parallel (10 jobs of ~500 subjects). Is it possible this could have slowed down the processing? I did notice that running Hippunfold on smaller data sets was much faster per subject. This data set includes ~21000 scans across ~11000 subjects. I previously ran Hippunfold on a smaller data set with 200 scans/subjects, and it ran much faster per subject and I only used one job.

Though I put the data subsets in different folders, the output folder is the same for everything. Is it possible many jobs accessing the same output folder at once could be causing crashes? If I created one output folder per job, could that reduce file i/o issues? 

In the last line of your message, which error are you referring to?
