### ISSUE TITLE
 Incomplete hippocampal volumes extraction

### ISSUE THREAD

**Issue by cyyyuyan** [khanlab/hippunfold#286]
Dear HippUnfold experts:
I have tried to segment the hippocampus based on T2w imaging using HippUnfold with singularity container in Linux. However, the results in the “anat” showed incomplete hippocampal subregions. It seemed like that too much tissue was trimmed during hippocampal cropping before the segmentations. In this condition, the segmented subregions of the hippocampus were lost some parts, and some slices of the hippocampus were not segmented yet. However, I’m not sure if it is the main reason.

Is the problem caused by smaller bounding box when cropping the left and the right hippocampus after data preprocessing? How about your suggestions to deal with this issue, such as how to set the fixed bounding box in the analysis index? Many thanks to your answers.

Since the T2w image in the test dataset has a limited FOV, I also make use of the --t1-reg-template command-line option.

**The analysis index I used is as following:**
**_singularity run -e khanlab_hippunfold_v1.2.0.sif test_cyy/sub-17_T2_1 sub17_hippunfold_t2w_0.45_1mm_t1w_0.7mm participant --modality T2w --t1-reg-template -p --cores all_**

The results were as below:
In the sagittal and coronal views, we can see some parts of the hippocampus were lost (the red arrow)
![c6S8iPwtHK](https://github.com/khanlab/hippunfold/assets/162542657/fbb645bc-8ad7-4b12-9f31-3f5ea82a3e70)

It seems like that this issue was caused by incomplete hippocampal volumes extraction during hippocampal cropping (the blue arrow)
![img_v3_028o_0f2184a5-77db-42e1-8ce7-fbd673f563fg](https://github.com/khanlab/hippunfold/assets/162542657/8d8c742d-2843-484e-a9bd-1bbd8afef8ef)

The registration between T1w and T2w images
![img_v3_028o_fd337aaa-8203-4791-976e-f20b7a87410g](https://github.com/khanlab/hippunfold/assets/162542657/0422a5d7-999d-4365-9559-df802d1a0e42)

**Comment by akhanf** [comment]
looks like the over-cropping is happening for the cropT2w space, not the corobl space the segmentation is actually performed in. If you extract the work tar.gz and check the corobl segmentations I bet those would look fine.. 

A fix was actually made for this in hippunfold v1.2.1  (https://github.com/khanlab/hippunfold/pull/224) - I see you're using an old version v1.2.0 -- I'd recommend switching to the latest release and that should hopefully be fixed. If not, the new version at least adds a new CLI parameter to specify the crop bounding box (below from docs):

```
--crop_native_res, --crop-native-res

    Sets the bounding box resolution for the crop native (e.g. cropT1w space). Under the hood, hippUnfold operates at higher resolution than the native image, so this tries to preserve some of that detail. (default: “0.2x0.2x0.2mm”)

    Default: “0.2x0.2x0.2mm”
--crop_native_box, --crop-native-box

    Sets the bounding box size for the crop native (e.g. cropT1w space). Make this larger if your hippocampi in crop{T1w,T2w} space are getting cut-off. This must be in voxels (vox) not millimeters (mm). (default: “256x256x256vox”)

    Default: “256x256x256vox”
```
