### ISSUE TITLE
transform the native hippocapus metrics to the unfolded space

### ISSUE THREAD

**Issue by raywell627** [khanlab/hippunfold#289]
Hi, 

I have successfully applied HippUnfold to the HCP-YA datasets, utilizing T1-weighted and T2-weighted images from native space to enhance the accuracy of hippocampal morphometry. I also looking to project functional data onto the surface. Given that the HCP volumetric fMRI data are primarily in MNI space, I transformed the hippocampal surface from T2-weighted space to MNI space using the 'wb_command `-surface-applywarpfield` command with the 'acpc2standard' warp field. Subsequently, I projected the fMRI data in MNI space onto the transformed hippocampal surface.
Can I  directly applied the transformed fmri hippocampal data to the unfolded space ?  Is there anything I should do for the unfoled surface files ? 
Thanks !

**Comment by jordandekraker** [comment]
Now that your subject surfaces are in space-MNI152, you can project the data onto surfaces with a tool like `wb_command -volume-to-sirface-mapping` and save as a func.gii file. You can then view the func.gii file on either the folded hippocampal surface or an unfolded surface (e.g. using freeview). There is vertex-correpondence between the folded and unfolded, so you can do all stats on the func.gii data without knowing the spatial position of the vertices which come from your transformed surf.gii files (though you may need it again for things like smoothing or cluster correction at the end of your analyses).

Let me know if that makes sense and if not I can give a more detailed step-by-step

**Comment by raywell627** [comment]
Thank you very much for your reply ! 
I have another small question. Can I assume that the vertices also have the same correspondence among different subjects after transformed them to the MNI space by using warpfield ? Can I directly perform vertex-level group comparison on the hippocampus by using the MNI space func.gii ?
Thanks

**Comment by jordandekraker** [comment]
Yes, that will work.

**Comment by raywell627** [comment]
Thanks for your quick reply !
