### ISSUE TITLE
Default Atlas

### ISSUE THREAD

**Issue by yeriguc** [khanlab/hippunfold#290]
Hi Jordan,

I hope you are well. I am writing to clear up a confusion I had. In the Hippunfold documentation,  it is written that when no atlas is specified in the command used to run hippunfold, multihist7 will be used as default. However, when I run it without specifying an the output files I get are in different sizes with the ones that I got from running hippunfold with --atlas multihist7. Additionally, I did not get the unfolded label nii.gz files when running hippunfold with the default atlas but I got them when running it with multihist7. 

This made me think that maybe the singularity image provided in the docs is not updated to the latest version since there is a discrepancy between the output and documentation.

Am I correct in my assumption?

Thank you for your time!

**Comment by jordandekraker** [comment]
Hi,

Thanks for the question. I believe all outputs should be identical whether you include `--atlas multihist7` or not (as long as you are useing a recent version). That is, they should have the same filenames and should be nearly* identical in contents. If this is not the case, can you ensure that there were no errors returned in the run that was missing outputs, and that a different output folder was specified for each run?

*may differ marginally between runs (e.g. by 1 voxel)

**Comment by yeriguc** [comment]
Hi,

Sorry for the late reply and thank you for your answer. I do not believe I had any errors in the run with the missing outputs. Yes, the differences in the sizes of the files were rather small so it should be due to the marginal differences between the runs. Maybe the missing files were indeed because I was using an old version accidentally. Is there any way to check which version of hippunfold an analysis was run in (like a log or json file)?

**Comment by jordandekraker** [comment]
you can run `hippunfold --version` to get the currently installed version, but i don't believe this is written in any output log files. 

It would be nice to add this to the log files (perhaps at the top of each log?). Perhaps that would be best to add to [snakebids](https://github.com/khanlab/snakebids) @akhanf thoughts?

**Comment by akhanf** [comment]
Yes I'll add a new issue to ensure we have some provenance about hippunfold version (and tag it v2.0 to push it along)..
