### ISSUE TITLE
Move Unet models to zenodo

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#30]
Not needed urgently, but at some point we can shift over to using zenodo.org to store our models (instead of dropbox..)

**Comment by jordandekraker** [comment]
Made a commit in my branch that should do the trick. 42d1a5a317e538d0084d1f4b3bb40a0ce10acdb0
Will still need to test in a fresh install though.

**Comment by akhanf** [comment]
resolved in #29
