### ISSUE TITLE
VTK and other files to native space

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#4]
Apply combined transform to cropped .vtk files using greedy.

Could also propagate a few other useful files, like coords-AP.nii.gz, coords-PS.nii.gz, and coords-IO.nii.gz

**Comment by akhanf** [comment]
Can definitely propagate the other images too. 

For the vtk let me let me know when you have the physical xfm issue sorted out within the corobl space.

**Comment by jordandekraker** [comment]
Just pushed the change that should have the xfm working correctly for generating .vtk files now. Still only about 80% sure that it'll work in all cases, but the nifti toolbox i'm using for matlab doesn't have a straightforward way to extract the correct xfm.

https://www.mathworks.com/matlabcentral/fileexchange/8797-tools-for-nifti-and-analyze-image (see xform_nii())

**Comment by jordandekraker** [comment]
pushed to Hippocampal_AutoTop that is. will still need to recompile, etc.

**Comment by akhanf** [comment]
Looks like it fixed the xfm issue.. 
However, something (likely unrelated) is that the midsurface doesn't actually appear in the mid-IO layer -- e.g.: 
![image](https://user-images.githubusercontent.com/11492701/99156860-6ebea280-2692-11eb-94ea-2b5f8dfe2287.png)

might be worthwhile generating both inner and outer surfaces as well, useful anyways, but also could be useful for debugging..

**Comment by royhaast** [comment]
I can confirm that this fixed the issue but see the same thing as @akhanf . @jordandekraker I remember we had a similar issue couple months ago and that there was an offset of 1 voxel (0.3 mm) in each direction. Screenshot below shows when applying these offsets in the LR (+1 voxel), AP (-1 voxel) and IS (-1 voxel) directions:
![midsurface](https://user-images.githubusercontent.com/22661001/99659677-7f3f9600-2a61-11eb-845e-6211cbbb8a6e.png)

Seems to align better?

**Comment by jordandekraker** [comment]
Good points, thanks. I'll add the inner and outer surface, and for the time being I can add +/-1 to the needed dimensions but I still haven't been able to identify where this off-by-1 issue comes from. I'll leave a TODO note in the code to this effect, and maybe we can leave this thread open until we can definitely nail down why this is occurring.

**Comment by royhaast** [comment]
Hi @jordandekraker, I had a look at your updated code and tested it but I think line 143 in coords_SurfMap.m should be like:
`v = reshape(v,[APres*PDres,3]) + [-1 -1 -1];` 
It looks fine after that change.

**Comment by jordandekraker** [comment]
Thank Roy! Just made the update

**Comment by akhanf** [comment]
closing this since all the gifti files are now provided, with folder structure finalized in #24
