### ISSUE TITLE
migrate mcr

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#5]
Migrate MCR compile from jordandekraker/Hippocampal_AutoTop to khanlab/hippunfold and have it procedurally compile when updating this submodule. This should make it easier to run local development in matlab in HAT (no concerns about forgetting to compile before pushing commits).

Ali suggested this should be done on a cloud storage system since binaries are large and compiling will require matlab2019b compiler

**Comment by jordandekraker** [comment]
another thought: can probably remove circle ci from jordandekraker/Hippocampal_AutoTop

**Comment by akhanf** [comment]
yeah definitely don't need circleci right now, I'll try to disable from my end

**Comment by akhanf** [comment]
re: compiling in CI, i'll think on it a bit -- would need a machine with matlab on it.. for now will just compile manually when needed..

**Comment by akhanf** [comment]
After PR #16 I have now re-enabled circleci builds for hippunfold, and will rely on compiled code from hippocampal_autotop
