### ISSUE TITLE
Surface resolution

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#53]
Current meshes are very high resolution.
We should create alternate versions, den-{den} for # of vertices, and provide all of them (or give options on cmdline).

128x256 currently
64x128 ?
32x64 ?
16x32 ?

https://github.com/jordandekraker/Hippocampal_AutoTop/blob/79f0d5540be2e1f23826f1079852cb8e1409b961/misc/unfold_ref_256x128x16.nii.gz

https://github.com/jordandekraker/Hippocampal_AutoTop/blob/79f0d5540be2e1f23826f1079852cb8e1409b961/tools/warps_gifti/create_template_unfold_gifti.m#L6

https://github.com/jordandekraker/Hippocampal_AutoTop/blob/79f0d5540be2e1f23826f1079852cb8e1409b961/tools/warps_gifti/create_template_unfold_gifti.m#L9

**Comment by jordandekraker** [comment]
I was thinking it would be good to generate a standard, decimated mesh that has roughly equal face sizes based on a group-averaged hippocampus. We could create a standard mapping of hippunfold vertices to the vertices of a decimated version.

In Boris' lab we will likely try to add an atlas for hippocampal surfaces to this toolbox: https://github.com/MICA-MNI/BrainStat.
This toolbox assumes face sizes are roughly equal, and for doing stats it would be nice to decimate a bit too since some bootstrapping tests can be compute heavy!

I'll try something like this and keep you posted!

**Comment by akhanf** [comment]
Yea I've been thinking about that too. Instead of creating an average surface and working with that (which has some downsides, e.g. blurring the anatomy), could alternatively update our unfolded standard mesh (equal face size in unfolded space), to have a triangulation with variable face sizes, based on the face size when transformed to native space. Those face sizes are the gyrification measures we compute already.. 

I've played around like this and still need to finish writing to a gifti, but the adaptive mesh looks like this (here I just used an average gyrification from ~30 subjects, but easy to swap that out for say all HCP training subjects).. Will commit in a branch once I iron the last few things out..
![adaptive_grid](https://user-images.githubusercontent.com/11492701/122766660-cd26b180-d26f-11eb-8a33-d4765c0b27f0.png)
With this approach we can set the target face size we want, so can easily generate different resolutions too. The one pictured here is ~16K vertices. This should also improve our surfaces in the really curved parts, since it ends up sampling much more densely than what we have in our existing scheme.

**Comment by jordandekraker** [comment]
Very nice! I think this could do the trick. 

Another approach that I explored a bit is a decimation algorithm. [In this case](https://github.com/alecjacobson/gptoolbox/blob/master/mex/decimate_libigl.m) the algorithm also produces roughly equal face sizes, doesn't add any new vertices, and keeps an index of which original vertices were kept. Here is an illustration using a 512x256 surface from 3D PLI (so going from 32K vertices down to 2K, but also note some vertices are lost in the corners):
![32K](https://user-images.githubusercontent.com/25106300/122806477-5ce05600-d298-11eb-8840-8ef001f4e09d.png)
![2K](https://user-images.githubusercontent.com/25106300/122806491-61a50a00-d298-11eb-88f9-b57a796bee5a.png)
![2K_sampPts](https://user-images.githubusercontent.com/25106300/122806503-649ffa80-d298-11eb-8ceb-8e24eda0285d.png)

**Comment by akhanf** [comment]
Yeah in the case where you have a single high-res surface I think doing decimation/re-meshing makes alot of sense. In general I think a combination of approaches is might be more optimal than either on their own. 
E.g. could start with a variably-meshed grid and also decimate in native space (then wouldn't require such a dense mesh to begin with).. 

However for the hippunfold (nnunet surfaces) we will probably want to use a group-average hippocampus, as the sampling for these single high-res cases is different enough (eg with all the digitations seen).. could probably confirm by comparing what a gyrification map looks like for this case compared to a nnunet hippunfold..

**Comment by akhanf** [comment]
Finally got around to tidying up the scripts and started a PR for creating the new templates with varying densities, and spacing adjusted to result in uniform (on average) meshes in native space.  Draft PR: #74 

If you want to see an example of these warped to a subject, they are here: 
https://github.com/khanlab/hippunfold/tree/custom-density/gen_unfold_template/example_transformed

and the new unfold templates are here:
https://github.com/khanlab/hippunfold/tree/custom-density/hippunfold/resources/unfold_template_avgarea

(note the naming of files in the example is by target vertex area, whereas it is density in the unfolded template, but they have 1-1 correspondence (e.g. 0.1mm^2 is 11k vertices)

**Comment by akhanf** [comment]
This is now resolved in #74
