### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by akhanf** [khanlab/hippunfold#67]
Just a reminder for us to update this, as it is out of date

**Comment by jordandekraker** [comment]
Relatedly, we should have the hippunfold usage print the version number! (especially now that we've had a few versions)

**Comment by akhanf** [comment]
> 

this might need to be a snakebids issue -- created this https://github.com/akhanf/snakebids/issues/85

**Comment by akhanf** [comment]
the readme has been updated in #139, will make another issue for dealing with the version number
