### ISSUE TITLE
suggestion: --skip_template-shape

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#68]
We're always losing a bit of precision (especially on digitations) with this step. I'd be curious to try an optional flag like this (as long as we have high confidence the nnunet segmentation is near perfect)

**Comment by akhanf** [comment]
yes, especially if we can also add some specific morphological checks/heuristics on the gm/src/sink labels..

adding the option should be easy, would just need to add an input function to the laplace rule, and pick the input file based on that..

**Comment by jordandekraker** [comment]
I think it would be challenging to get a really good heuristic for whether or not template-shape should be run. One simple check could be just to see whether all labels exist in the nnunet output, but this still doesn't guarantee they meet all the criteria. The second potential tool is f3d registration to the CITI mask to ensure there is decent Dice overlap in whole hippocampal volume. 

Neither of those check are perfect though, either for template-shape or for the whole pipeline in general. 

A bad set of Laplace source/sink labels will generate weird surface files, which could be a third QA heuristic too.

**Comment by akhanf** [comment]
I wasn't thinking specifically of a heuristic to decide whether shape injection is done, but rather to perform post-processing fixes based on morphological operations, or flags to stop.. If we use shape injection only on some subset of subjects I worry that it would induce a bias between those and the other subjects.. 

The other thing we should also evaluate in the context of retaining digitations is the level of regularization for the greedy shape inject registration -- right now it is just default parameters.. 

In any case, I have an open PR to nomatlab here that implements the option: #71

**Comment by jordandekraker** [comment]
Closing with https://github.com/khanlab/hippunfold/pull/83
