### ISSUE TITLE
template surfaces on zenodo

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#79]
This should provide an easy way for other apps (eg. BrainStat) to pull a standard set of surfaces.

I'll also aim to provide a group-averaged sample folded surface

**Comment by jordandekraker** [comment]
TODO: make group-averaged folded surface be in space-CITI168 so users can see it on a relevant underlay

**Comment by akhanf** [comment]
Having it in MNI2009c space would be more generally useful, I found that just running hippunfold on the template is a reasonable way to get that surface. 

The group-averaged surface (if you did surface-based averaging) would be out of alignment with the template image, would it not?

**Comment by akhanf** [comment]
Haven't added any links to it in the docs yet, but this is partially addressed in https://github.com/khanlab/hippunfold-templateflow

There I just ran hippunfold directly on the templateflow templates, and sharing the resulting segmentations and surfaces in that github repo. Not the same as generating an average hippocampus, but still provides an easy way to use hippocampal surfaces from template-normalized data.
