### ISSUE TITLE
filter and path confusion

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#80]
I keep getting mixed up when I try to run hippunfold on data with multiple sessions. I suspect this is an issue with snakebids and not hippunfold, but I'll raise it here anyway. 

If I add something like `--filter_T1w session=01` then I get an error that session=02 input could not be found for rule copy_to_results

If instead add something like `--path_T1w BIDS_MICs/rawdata/sub-{subject}/ses-01/anat/sub-{subject}_ses-01_T1w.nii.gz` then it runs all sessions AND all subjects (even when i have `-participant_label HC001`). If I also add the above filter_T1w then it still runs all subjects and all sessions. 

Worst of all, if I run with no flags then I get an error:
```MissingInputException: Missing input files for rule copy_to_results:
work/sub-HC001/ses-02/anat/sub-HC001_ses-02_desc-preproc_T1w.nii.gz
InputFunctionException (rule import_t1, line 5, /data/mica3/jordand/testinground/hippunfold/hippunfold/workflow/rules/preproc_t1.smk):
    Error:
      IndexError: list index out of range
    Wildcards:
      subject=HC001
      session=02
```
I believe the index is out of range because the input at [0] doesn't exist. 

Part of the issue may be that ses-02 has run-1 and run-2, whereas ses-01 has only one run (and therefore it is not in the filename).

Any ideas @akhanf ?

**Comment by akhanf** [comment]
With your bids dataset you will have to use `--path_*` (and not `--filter_*`) for your inputs, since the snakebids+pybids grabbing will fail since not all subjects have the same data.. 

Prior to snakebids 0.3.10 the `--participant_label` option did not have an effect when using `--path_*`, but that should be fixed if you are using the latest hippunfold? 

I'll give it a try myself with a dummy dataset to see how it works

**Comment by akhanf** [comment]
When I try it out, the `--participant_label` option with `--path_*` it works fine for me:
```
hippunfold - test_out participant  --path_T1w /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore.nii.gz --participant_label 100307 --path_T2w /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T2w_acpc_dc_restore.nii.gz -np
```

What is the exact command you are trying and what hippunfold version are you using?

**Comment by jordandekraker** [comment]
Hmm I'll keep an eye on it and let you know if I can replicate the issue.

I also wanted to bring up another quick path/wildcard issue: when running `--modality cropseg` there may be multiple subject, some with only `hemi-L` and some with only `hemi-R`. Currently this doesn't run (the `--hemi` would need to depend on the subject)

**Comment by jordandekraker** [comment]
I also haven't been able to reproduce this issue anymore, will close.
