### ISSUE TITLE
faster laplace solver through image pyramids

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#85]
@akhanf has some code to do this already, check out his old nomatlab (I think?) branch

This is really only an issue when running with no initialization (ie. skip_template_shape_injection)

**Comment by akhanf** [comment]
I located where the snakefile with multi-res laplace is, it is actually in master already here:

https://github.com/khanlab/hippunfold/blob/master/hippunfold/resources/tpl-upenn/Snakefile

There is a rule to downsample coords:
 https://github.com/khanlab/hippunfold/blob/49a2245d3fbf5b52c3955a7909a3af38d72041f0/hippunfold/resources/tpl-upenn/Snakefile#L26

Run laplace without initialization at the lowest resolution:
https://github.com/khanlab/hippunfold/blob/49a2245d3fbf5b52c3955a7909a3af38d72041f0/hippunfold/resources/tpl-upenn/Snakefile#L37

Then upsample coords:
https://github.com/khanlab/hippunfold/blob/49a2245d3fbf5b52c3955a7909a3af38d72041f0/hippunfold/resources/tpl-upenn/Snakefile#L72

and run Laplace with init coords:
https://github.com/khanlab/hippunfold/blob/49a2245d3fbf5b52c3955a7909a3af38d72041f0/hippunfold/resources/tpl-upenn/Snakefile#L54

The number of levels is defined by setting the wildcard constraints in the level wildcard, e.g. right now lowest res is level 2 (downsampled by 50% twice; level 1 is downsampled once, level 0 is original resolution)..

**Comment by akhanf** [comment]
speed-up by fast marching initialization #88 obviates the need for this right now, so closing this issue
