### ISSUE TITLE
Hanging on rule create_warps

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#92]
This is happening only with very high resolution data (46x46x60um). I tried increasing the resources from 16gb to 96gb memory but still same problem (and in the system monitor it doesn't appear to use this all anyway). I can also see this is using a single core, but I've left it running for a whole week and never got an output. 

I know the interpolation step can be somewhat memory-intensive, so perhaps this is the issue?

**Comment by jordandekraker** [comment]
Looking more into this, it seems each call to scipy's `interpolation.griddata` generates a subprocess that doesn't clear after we evaluate it. In this case each takes ~40gb and a very long time to complete, likely exceeding the resources allocated by snakebids. I opened a branch to try and run and then clear these serially to save memory https://github.com/khanlab/hippunfold/tree/create_warps_resource_manage.

If this makes sense and work then I'll make a PR and we can do some further refining

**Comment by akhanf** [comment]
Yes sounds like it needs more memory than available.. 

But is it getting past the first griddata call? If so, then maybe clearing things up might help, but I suspect it's the first griddata call that is causing it to hang.. 

I doubt there would be much you can do except use a large memory system (can check the griddata code to see what it needs to allocate), try to work with downsampled data for this step, or perform this interpolation on chunks of the image at a time..

**Comment by jordandekraker** [comment]
Now that we identified the real problem (see https://github.com/khanlab/hippunfold/pull/94), closing this issue
